export const PREFIX = "@@deficiency/";

export const ASYNC_DEFICIENCY_INIT = `${PREFIX}ASYNC_DEFICIENCY_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const GET_ALL_DEFICIENCY = `${PREFIX}GET_ALL_DEFICIENCY`;
