export const PREFIX = "@@product/";

export const ASYNC_PRODUCT_INIT = `${PREFIX}ASYNC_PRODUCT_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;
export const INITIALIZE_PRODUCT = `${PREFIX}INITIALIZE_PRODUCT`;

export const GET_ALL_PRODUCTS = `${PREFIX}GET_ALL_PRODUCTS`;
