export const PREFIX = "@@product/";

export const ASYNC_RESEARCH_INIT = `${PREFIX}ASYNC_RESEARCH_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;
export const INITIALIZE_RESEARCH = `${PREFIX}INITIALIZE_RESEARCH`;

export const GET_ALL_RESEARCHES = `${PREFIX}GET_ALL_RESEARCHES`;
