export const PREFIX = "@@verification/";

export const ASYNC_VERIFICATION_INIT = `${PREFIX}ASYNC_VERIFICATION_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;
export const INITIALIZE_VERIFICATION = `${PREFIX}INITIALIZE_VERIFICATION`;

export const GET_ALL_VERIFICATIONS = `${PREFIX}GET_ALL_VERIFICATIONS`;
export const GET_SINGLE_VERIFICATION = `${PREFIX}GET_SINGLE_VERIFICATION`;
export const ON_CHANGE_FIELDS = `${PREFIX}ON_CHANGE_FIELDS`;
export const ON_CHANGE_PRODUCT = `${PREFIX}ON_CHANGE_PRODUCT`;
